<?php
/**
 * @file
 * Drupal Module: simple_print
 * Adds a printable version to your pages.
 */
 
/**
 * Implementation of hook_preprocess_page().
 */
function sprint_init() {
  drupal_add_js(drupal_get_path('module', 'sprint') .'/sprint.js');
  drupal_add_css(drupal_get_path('module', 'sprint') .'/sprint.css');
  drupal_add_css(drupal_get_path('module', 'sprint') . '/sprint-print.css', array('group' => CSS_DEFAULT, 'media' => 'print'));
}
